// Code generated by protoc-gen-go.
// source: servicepb/feedback.proto
// DO NOT EDIT!

package servicepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JobRef struct {
	JobId  uint64 `protobuf:"varint,1,opt,name=job_id" json:"job_id,omitempty"`
	NodeId uint64 `protobuf:"varint,2,opt,name=node_id" json:"node_id,omitempty"`
}

func (m *JobRef) Reset()         { *m = JobRef{} }
func (m *JobRef) String() string { return proto.CompactTextString(m) }
func (*JobRef) ProtoMessage()    {}

type JobStartedRequest struct {
	Job *JobRef `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *JobStartedRequest) Reset()         { *m = JobStartedRequest{} }
func (m *JobStartedRequest) String() string { return proto.CompactTextString(m) }
func (*JobStartedRequest) ProtoMessage()    {}

func (m *JobStartedRequest) GetJob() *JobRef {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobStartedResponse struct {
}

func (m *JobStartedResponse) Reset()         { *m = JobStartedResponse{} }
func (m *JobStartedResponse) String() string { return proto.CompactTextString(m) }
func (*JobStartedResponse) ProtoMessage()    {}

type JobProgressStep struct {
	Job    *JobRef                 `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
	Output *JobProgressStep_Output `protobuf:"bytes,2,opt,name=output" json:"output,omitempty"`
}

func (m *JobProgressStep) Reset()         { *m = JobProgressStep{} }
func (m *JobProgressStep) String() string { return proto.CompactTextString(m) }
func (*JobProgressStep) ProtoMessage()    {}

func (m *JobProgressStep) GetJob() *JobRef {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *JobProgressStep) GetOutput() *JobProgressStep_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type JobProgressStep_Output struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (m *JobProgressStep_Output) Reset()         { *m = JobProgressStep_Output{} }
func (m *JobProgressStep_Output) String() string { return proto.CompactTextString(m) }
func (*JobProgressStep_Output) ProtoMessage()    {}

type JobProgressResponse struct {
}

func (m *JobProgressResponse) Reset()         { *m = JobProgressResponse{} }
func (m *JobProgressResponse) String() string { return proto.CompactTextString(m) }
func (*JobProgressResponse) ProtoMessage()    {}

type JobStoppedRequest struct {
	Job *JobRef `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *JobStoppedRequest) Reset()         { *m = JobStoppedRequest{} }
func (m *JobStoppedRequest) String() string { return proto.CompactTextString(m) }
func (*JobStoppedRequest) ProtoMessage()    {}

func (m *JobStoppedRequest) GetJob() *JobRef {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobStoppedResponse struct {
}

func (m *JobStoppedResponse) Reset()         { *m = JobStoppedResponse{} }
func (m *JobStoppedResponse) String() string { return proto.CompactTextString(m) }
func (*JobStoppedResponse) ProtoMessage()    {}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for FeedbackService service

type FeedbackServiceClient interface {
	// JobStarted notifies the master that the job has started on given node
	JobStarted(ctx context.Context, in *JobStartedRequest, opts ...grpc.CallOption) (*JobStartedResponse, error)
	JobProgress(ctx context.Context, opts ...grpc.CallOption) (FeedbackService_JobProgressClient, error)
	// JobStopped notifies the master that the job has stopped on given node
	JobStopped(ctx context.Context, in *JobStoppedRequest, opts ...grpc.CallOption) (*JobStoppedResponse, error)
}

type feedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackServiceClient(cc *grpc.ClientConn) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) JobStarted(ctx context.Context, in *JobStartedRequest, opts ...grpc.CallOption) (*JobStartedResponse, error) {
	out := new(JobStartedResponse)
	err := grpc.Invoke(ctx, "/servicepb.FeedbackService/JobStarted", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) JobProgress(ctx context.Context, opts ...grpc.CallOption) (FeedbackService_JobProgressClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FeedbackService_serviceDesc.Streams[0], c.cc, "/servicepb.FeedbackService/JobProgress", opts...)
	if err != nil {
		return nil, err
	}
	x := &feedbackServiceJobProgressClient{stream}
	return x, nil
}

type FeedbackService_JobProgressClient interface {
	Send(*JobProgressStep) error
	CloseAndRecv() (*JobProgressResponse, error)
	grpc.ClientStream
}

type feedbackServiceJobProgressClient struct {
	grpc.ClientStream
}

func (x *feedbackServiceJobProgressClient) Send(m *JobProgressStep) error {
	return x.ClientStream.SendMsg(m)
}

func (x *feedbackServiceJobProgressClient) CloseAndRecv() (*JobProgressResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(JobProgressResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *feedbackServiceClient) JobStopped(ctx context.Context, in *JobStoppedRequest, opts ...grpc.CallOption) (*JobStoppedResponse, error) {
	out := new(JobStoppedResponse)
	err := grpc.Invoke(ctx, "/servicepb.FeedbackService/JobStopped", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedbackService service

type FeedbackServiceServer interface {
	// JobStarted notifies the master that the job has started on given node
	JobStarted(context.Context, *JobStartedRequest) (*JobStartedResponse, error)
	JobProgress(FeedbackService_JobProgressServer) error
	// JobStopped notifies the master that the job has stopped on given node
	JobStopped(context.Context, *JobStoppedRequest) (*JobStoppedResponse, error)
}

func RegisterFeedbackServiceServer(s *grpc.Server, srv FeedbackServiceServer) {
	s.RegisterService(&_FeedbackService_serviceDesc, srv)
}

func _FeedbackService_JobStarted_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(JobStartedRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(FeedbackServiceServer).JobStarted(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _FeedbackService_JobProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FeedbackServiceServer).JobProgress(&feedbackServiceJobProgressServer{stream})
}

type FeedbackService_JobProgressServer interface {
	SendAndClose(*JobProgressResponse) error
	Recv() (*JobProgressStep, error)
	grpc.ServerStream
}

type feedbackServiceJobProgressServer struct {
	grpc.ServerStream
}

func (x *feedbackServiceJobProgressServer) SendAndClose(m *JobProgressResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *feedbackServiceJobProgressServer) Recv() (*JobProgressStep, error) {
	m := new(JobProgressStep)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FeedbackService_JobStopped_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(JobStoppedRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(FeedbackServiceServer).JobStopped(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _FeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobStarted",
			Handler:    _FeedbackService_JobStarted_Handler,
		},
		{
			MethodName: "JobStopped",
			Handler:    _FeedbackService_JobStopped_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JobProgress",
			Handler:       _FeedbackService_JobProgress_Handler,
			ClientStreams: true,
		},
	},
}
