// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	ScheduleResponse
	Job
	Jobs
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ScheduleResponse struct {
}

func (m *ScheduleResponse) Reset()         { *m = ScheduleResponse{} }
func (m *ScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*ScheduleResponse) ProtoMessage()    {}

type Job struct {
	Name        string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CommandLine string   `protobuf:"bytes,2,opt,name=command_line" json:"command_line,omitempty"`
	When        string   `protobuf:"bytes,3,opt,name=when" json:"when,omitempty"`
	Tags        []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}

type Jobs struct {
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *Jobs) Reset()         { *m = Jobs{} }
func (m *Jobs) String() string { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()    {}

func (m *Jobs) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}
